config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :videos
  resources :contacts, :only => [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file, :attachment => true
  attribute :message
  attribute :nickname, :captcha => true

  def headers
    {
        :subject => "Contact Form",
        :to => ENV["EMAIL"],
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, :styles => {:large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :public_posts, -> { where(public: true) }

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, :styles => {:large => "600x600>", :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["video/mp4", "image/jpg", "image/jpeg"] 
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_form_params)
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Can not send Message"
      render :new
    end
  end

  private 
  def contact_form_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @public_posts = Post.public_posts.order("created_at DESC").page(params[:page]).per(3)
    @posts = Post.order("created_at DESC").page(params[:page]).per(3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, :notice => "Blog was saved!"
    else
      render 'new', :notice => "Shit don't work"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Blog updated/saved"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :slug, :image, :public)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  def index
    @projects = Project.all.order("created_at DESC").page(params[:page]).per(3)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "success!"
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project updated/saved"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug, :image)
  end

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :find_video, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  def index
    @videos = Video.order("created_at DESC")
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to @video, :notice => "Screen cast was saved!"
    else
      render 'new', :notice => "shit don't work"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to @video, :notice => "Video updated/saved"
    else
      render 'edit'
    end
  end

  def destroy
    if @video.destroy
      redirect_to videos_path
    end
  end

  private

  def video_params
    params.require(:video).permit(:title, :notes, :image)
  end

  def find_video
    @video = Video.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @public_posts = Post.public_posts.limit(3).order("created_at DESC")
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
    @videos = Video.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title"> Got Questions? Ask me!</h1>
<div class="skinny_wrapper wrapper_padding">
  <p>Message sent!</p>
  <p>Talk to you soon :)</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title"> Got Questions? Ask me!</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_field :name, required: true %>

    <br>

    <%= f.label :email %> <br>
    <%= f.text_field :email, required: true %>

    <br>

    <%= f.label :message %> <br>
    <%= f.text_area :message, as: :text %>

    <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: 'blank field' %>
    </div>

    <%= f.submit 'Send Message', class: "button" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alexande Lee - Web Developer // Software Engineer</title>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <header class="main_navigation clearfix">
    <%= link_to "Alexander Lee", root_path, :class => "name"%>

    <a href="#" class="main_navigation__hamburger"><i class="fa fa-bars"></i></a>

    <nav class="main_navigation__personal-information">
      <%= link_to "Blogs", posts_path %>
      <%= link_to "Projects", projects_path %>
      <%= link_to "ScreenCast", videos_path %>
      <%= link_to "Contact", new_contact_path %>

      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </nav>
  </header>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>

  <footer class="main_footer">
    <nav class="main_footer__links">
      <a href="https://twitter.com/kkomaz" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://www.linkedin.com/in/alexanderlee2" target="_blank"><i class="fa fa-linkedin"></i></a>
      <a href="https://github.com/kkomaz" target="_blank"><i class="fa fa-github"></i></a>
    </nav>

    <p class="main_footer__copyright">
        &copy; 2015 Alexander Lee
    </p>
  </footer>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'alexjlee';
    var disquis_identifier = '<%= @post.id %>'
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving: </h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "Title" %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :image, "Image" %> <br>
  <%= f.file_field :image %>

  <br>
  <br>

  <%= f.label :content, "Write your blog post here" %><br>
  <%= f.text_area :content %>

  <%= f.check_box :public %>
  <%= f.label :public, "Public?" %>

  <br>
  <br>

  <%= f.submit "Submit your Blog" %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title"> My Blog Posts</h1>

<div id="post_wrapper" class="skinny_wrapper">
  <% if user_signed_in? %>
    <div id="new_links">
      <%= link_to "Create New Post", new_post_path %>
    </div>

    <div class="posts">
      <% @posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B, %d') %></p>

        <h2><%= link_to post.title, post %></h2>

        <%= image_tag post.image.url(:medium) %>

        <div id="admin_links">
          <%= link_to "Edit", edit_post_path(post) %>
          <%= link_to "Destroy", post_path(post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
        </div>
        <hr>
      </div>
      <% end %>
    </div>
  <% else %>
    <div class="posts">
      <% @public_posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B, %d') %></p>

        <h2><%= link_to post.title, post %></h2>

        <%= image_tag post.image.url(:medium) %>
        
        <hr>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= paginate @posts%>
<% else %>
  <%= paginate @public_posts %>
<% end %>

app/views/posts/show.html.erb
<div class="post-page">
  <header>
    <p class="post-page__date"><%= @post.created_at.strftime('%A, %B, %d') %></p>
    <h1><%= @post.title %></h1>
    <%= image_tag @post.image.url(:large) %>
  <hr>
  </header>

<div class="post-page__content">
<p><%= markdown(@post.content) %></p>
</div>

<hr>

<div class="post-page__share_box">
  <p>Share <%= @post.title %></p>
    <% if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit", edit_post_path(@post) %>
        <%= link_to "Destroy", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
      </div>
    <% end %>
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @kkomaz - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
</div>

<hr>

<%= render 'disqus' %>

</div>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error")%> prevented this project from saving: </h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "Title" %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :image, "Image" %> <br>
  <%= f.file_field :image %>

  <br>
  <br>
  
  <%= f.label :description, "Write your description" %><br>
  <%= f.text_area :description %>

  <br>
  <br>

  <%= f.label :link, "Link" %>
  <%= f.text_field :link %>

  <%= f.submit "Submit your Blog" %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title"> My Projects</h1>
<div id="post_wrapper" class="skinny_wrapper">
  <% if user_signed_in? %>
    <div id="new_links">
      <%= link_to "Create New Project", new_project_path %>
    </div>
  <% end %>

  <div class="post">
    <% @projects.each do |project| %>
    <p class="date"><%= project.created_at.strftime('%A, %B, %d') %></p>

    <h2><%= link_to project.title, project %></h2>

    <%= image_tag project.image.url(:medium) %>

    <% if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit", edit_project_path(project) %>
        <%= link_to "Destroy", project_path(project), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
      </div>
    <% end %>

    <hr>
  <% end %>
  </div>
</div>
</div>
<%= paginate @projects%>

app/views/projects/new.html.erb
<h1 id="page_title">New Post</h1>
<h3><%= link_to "Create New Post", new_post_path %></h3>
<div class="skinny_wrapper wrapper_padding">
  
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %B, %d') %></p>
    <h1><%= @project.title %></h1>
    <%= image_tag @project.image.url(:large) %>
  <hr>
  </header>

<div id="content">
  <%= markdown(@project.description) %>
  <div class="share_box">
  <% if user_signed_in? %>
    <%= link_to "Edit", edit_project_path(@project) %>
    <%= link_to "Destroy", project_path(@project), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
  <% end %>
  </div>
  <div class="button_wrapper">
    <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
  </div>
</div>

<hr>
</div>

app/views/videos/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'alexjlee';
    var disquis_identifier = '<%= @video.id %>'
    var disqus_title = '<%= @video.title %>';
    var disqus_url = '<%= url_for([@video, {only_path: false}]) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
  <% if @video.errors.any? %>
    <h2><%= pluralize(@video.errors.count, "error")%> prevented this video from saving: </h2>
    <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title, "Title" %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :image, "Image" %> <br>
  <%= f.file_field :image %>

  <br>
  <br>
  
  <%= f.label :notes, "Write your notes here" %><br>
  <%= f.text_area :notes %>

  <br>
  <br>

  <%= f.submit "Submit your notes" %>

<% end %>

app/views/videos/edit.html.erb
<h1 id="page_title">Edit Video</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/videos/index.html.erb
<h1 id="page_title"> My Screencasts</h1>
<div id="post_wrapper" class="skinny_wrapper">
  <% if user_signed_in? %>
  <div id="new_links">
    <%= link_to "Create New Video", new_video_path %>
  </div>
  <% end %>
  <% if !@videos.empty? %>
  <% @videos.each do |video| %>
  <div class="post">    
    <p class="date"><%= video.created_at.strftime('%A, %B, %d') %></p>
    <h2><%= link_to video.title, video %></h2>
      <% if user_signed_in? %>
        <div id="admin_links">
          <%= link_to "Edit", edit_video_path(video) %>
          <%= link_to "Destroy", video_path(video), method: :delete, data: {confirm: "Are you sure you want to delete this video?"} %>
        </div>
      <% end %>
    <hr>
    <% end %>
  </div>
  <% else %>
    Coming soon...
  <% end %>
</div>

     

app/views/videos/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/videos/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @video.created_at.strftime('%A, %B, %d') %></p>
    <h1><%= @video.title %></h1>
        <%= video_tag @video.image.url, :id => "style_image" %>
  <hr>
  </header>

<div id="content">
<p><%= markdown(@video.notes) %></p>
</div>

<hr>

<div class="share_box">
  <p>Share <%= @video.title %></p>
    <% if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit", edit_video_path(@video) %>
        <%= link_to "Destroy", video_path(@video), method: :delete, data: {confirm: "Are you sure you want to delete this video?"} %>
      </div>
    <% end %>
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @video.title %> by @kkomaz - &amp;url=<%= url_for([@video, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@video, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@video, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
</div>

<hr>

<%= render 'disqus' %>

<script>
  var video = document.getElementById("style_image");

  $('#style_image').hover(function toggleControls() {
    if (video.hasAttribute("controls")) {
        video.removeAttribute("controls")
    } else {
        video.setAttribute("controls", "controls")
    }
  })
</script>

app/views/welcome/_post.html.erb
<h3><%= link_to post.title, post_path(post) %></h3>
<p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>

app/views/welcome/_projects.html.erb
<h3><%= link_to project.title, project_path(project) %></h3>
<p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>

app/views/welcome/_videos.html.erb
<h3><%= link_to video.title, video_path(video) %></h3>
<p class="date"><%= video.created_at.strftime("%A, %b, %d") %></p>

app/views/welcome/index.html.erb
<div class="welcome-page">
  <div class="homepage-banner" style="visibility: visible">
    <div class="homepage-banner__description">
      <h1 class="homepage-banner__name">Hi, I'm Alexander Lee</h1>
      <p class="homepage-banner__job">I am a Web Developer // Software Engineer </p>
    </div>
  </div>

  <div class="user-information">
    <div class="user-information__header">
      <h2 class="user-information__label">About me</h2>
      <hr>
    </div>

    <div class="user-information__image">
      <div class="user-img">
        <%= image_tag("profile2.png", class: "optional_class") %>
      </div>
    </div>

    <div class="user-information__content">
      <p>
        I am a full-stack Web Developer // Software Engineer living in New York.
      </p>

      <p>
        I build websites and web applications using Ruby on Rails and various different frameworks such as React, Backbone, and Angular
      </p>

      <p>
        Who doesn't like css? :)
      </p>

      <p>
      This website is dedicated to showing my readers what I have been working on as well as some cool blog posts that I find interesting and helpful.
      </p>

      <p>
      I hope my posts will get you excited about being developer!
      </p>

      <p>
      You can follow me on github or linkedin on the links in the bottom right corner!
      </p>
    </div>
  </div>

  <div class="user-content">
    <div class="user-content__blog-posts">
      <h2>My Blog Posts</h2>
      <hr>
      <% if user_signed_in? %>
        <%= render partial: "welcome/post", collection: @posts, :as => "post" %>
      <% else %>
        <%= render partial: "welcome/post", collection: @public_posts, :as => "post" %>
      <% end %>
      <%= link_to "My previous blog site", "https://kkomaz.wordpress.com/category/blogs/", :target => "_blank" %>
    </div>

    <div class="user-content__projects">
      <h2>My Projects</h2>
      <hr>
      <%= render partial: "welcome/projects", collection: @projects, :as => "project" %>
    </div>

    <div class="user-content__screencast">
      <h2>My Screencasts</h2>
      <hr>
      <% if !@videos.empty? %>
        <%= render partial: "welcome/videos", collection: @videos, :as => "video" %>
      <% else %>
        Coming soon...
      <% end %>
    </div>
  </div>
</div>